name: Attach ZIP to GitHub Release

on:
  release:
    types:
      - published

jobs:
  attach-zip:
    name: Attach ZIP to release
    runs-on: ubuntu-latest
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          tools: composer:v2
          coverage: none
      - name: Checkout
        uses: actions/checkout@v3
      - name: Create and attach ZIP
        uses: concrete5-community/gh-package-release-attach@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          remove-files: |
            composer.json
            composer.lock
          keep-files: |
            README.md
